### ISSUE TITLE
Add support for cgroups v2

### ISSUE THREAD

**Issue by strategicpause** [strategicpause/cgstat#3]
#### Description
Today cgstat only has support for cgroups v1, which limits its usefulness to only systems using that version. As cgroups v2 adoption grows, we'll want to not just add support for it, but also include new stats which were introduced.

#### Tasks

- [x] Come up with the mechanism used to detect cgroups v2. Should the user specify it, or should cgstat detect it (preference for the second since v1 vs v2 is a binary choice)
- [ ] Come up with the stats to display for normal mode, verbose mode, and csv output.
- [ ] Make changes. [Commit 2e4c26a](https://github.com/strategicpause/cgstat/commit/2e4c26a09aa436d71b15e41dfdaaf61820a72f84) has already stared some refactoring that starts to divide code up into separate v1 and v2 packages, which cgroups v2 support can build on top of.

**Comment by strategicpause** [comment]
[containerd/cgroups](https://github.com/containerd/cgroups) seems to have a `Mode()` function which can answer this ([Source](https://github.com/containerd/cgroups/blob/157c4da5ef3aac5fd7229b5ff3e13a8c0ee857d4/utils.go#L55-L76)). Opting to use this as the mechanism to detect which mode the host is running on.

**Comment by strategicpause** [comment]
[Commit 4b5cd979](https://github.com/strategicpause/cgstat/commit/4b5cd9792fd77df45a392a7d6fcbdeaf98d04d07) introduces the start of cgroups v2 support. This is mostly a refactoring of existing code to help generalize some of the code for reading / outputting stats regardless of cgroups version type.

**Comment by strategicpause** [comment]
[This article from Indeed](https://engineering.indeedblog.com/blog/2019/12/unthrottled-fixing-cpu-limits-in-the-cloud/) has some good ideas for what could be useful for output. One metric that they came up with to troubleshoot performance issues is the throttled percentage metric (`nr_throttled / nr_periods`) to tell them what percentage of periods processes within a cgroup were throttled.

The example they gave was a cgroup which used 0.4 vCPU (40 ms, assuming 100ms period). For a request which took 200ms to complete, it would be throttled each period and end up actually taking 5 periods to complete (40ms from each period), which resulted in the request actually taking 440ms.

**Comment by strategicpause** [comment]
Standard output:
- Cgroup Name
- CPU Usage
- NumThrottledPeriods / NumRunnablePeriods (Percentage)
- Current PIDS / Limit (Percentage)
- Memory Usage / Memory Limit (Percentage)
- Anon Memory (Percentage of Memory Limit)
- File Memory (Percentage of Memory Limit)
- Memory High
- Memory Max
- MemoryLow
- Oom Kill Events

Note: (Percentage) indicates a percentage will be included with the usage / limit value.

**Comment by strategicpause** [comment]
Basic support has been added in view mode. Still need to look at verbose mode.
